version: '3'
services:
  mysql:
    restart: always
    image: mysql:latest
    container_name: my_mysql
    security_opt:
      - seccomp:unconfined
    volumes:
      - /data/docker/mysql/data:/var/lib/mysql
      - /data/docker/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      # 设置密码
      - "MYSQL_DATABASE=mydb"
      # 设置默认数据库
      - "TZ=Asia/Shanghai"
    ports:
      - 127.0.0.1:3306:3306
