version: "3"
services:
  nginx:
    image: nginx:alpine
    restart: always
    container_name: mynginx
    privileged: true
    ports:
      - 8080:8080
      - 8090:8090
    volumes:
      - /data/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /data/docker/nginx/html:/usr/share/nginx/html
      - /data/docker/nginx/logs:/var/log/nginx/
      - /data/docker/nginx/ssl:/ssl/
      - /data/docker/nginx/conf.d:/etc/nginx/conf.d/
      - /data/back:/data/files
    environment:
      TZ: Asia/Shanghai
    networks:
      - web-net
      
  php:
    image: php:7.3-fpm
    privileged: true
    container_name: php-fpm
    restart: always
    volumes:
      - /data/docker/nginx/html:/web
      - /data/docker/nginx/php.ini:/etc/php/7.3/fpm/php.ini
    networks:
      - web-net
      
  mysql:
    image: mysql
    restart: always
    ports:
      - 127.0.0.1:3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - web-net
      
networks: 
  web-net:
  
