version: '3'
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer-ce
    restart: always
    ports:
      - '8000:8000'
      - '9000:9000'
    volumes:
      - /data/docker/portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    command: -H unix:///var/run/docker.sock

volumes:
    portainer_data:
