version: '3'
services:
  redis:
    image: redis
    container_name: docker_redis
    volumes:
      - /data/docker/redis/data:/data
      - /data/docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - /data/docker/redis/logs:/logs
    command:
      /bin/bash -c "redis-server /usr/local/etc/redis/redis.conf"
    ports:
      - 6379:6379


# 'redis-server' '--requirepass' 'FA9yRd3RWbQMQFU'
