version: "3"
services:
  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    ports:
      - ${nginx_port}:80
    volumes:
      - ${DOCKER_PATH}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${DOCKER_PATH}/nginx/html:/usr/share/nginx/html
      - ${DOCKER_PATH}/nginx/logs:/var/log/nginx/
      - ${DOCKER_PATH}/nginx/ssl:/ssl/
      - ${DOCKER_PATH}/nginx/conf.d:/etc/nginx/conf.d/
    environment:
      TZ: Asia/Shanghai
